### ISSUE TITLE
Map with parcels and landuse

### ISSUE THREAD

**Issue by davemfish** [natcap/urban-online-workflow#1]
Map that displays parcel boundaries, allows selection of 1 or more parcels and collects their geometries to send to a server.

The parcel data is still TBD. We may end up using this service: https://regrid.com/api/plans

But for now we can develop against this: https://opendata-cosagis.opendata.arcgis.com/datasets/CoSAGIS::cosa-zoning/explore?location=29.435622%2C-98.518921%2C10.89

LULC rasters will ultimately be served from our infrastructure.

**Comment by davemfish** [comment]
If we start out using the COSA data, we'll need to tile it and serve it ourselves. It's just too big to display without tiles.

**Comment by phargogh** [comment]
Related: #5
