### ISSUE TITLE
Urban Nature Access: Gather input data

### ISSUE THREAD

**Issue by davemfish** [natcap/urban-online-workflow#110]
See the list of data requirements here: https://github.com/natcap/urban-online-workflow/wiki/Data-for-InVEST,-by-model#urban-nature-access

**Comment by chrisnootenboom** [comment]
**Population**: I've created national 2020 population density map from decennial census
**Administrative boundaries**: Census Blocks
**Demand**: 16.7m2/person (higher than 9m2 suggested in User’s Guide, used in SA Report)
**Search Radius**: 2230m (used in SA Report)

**Comment by davemfish** [comment]
Chris and Lingling have completed this. See details in our data readme: https://docs.google.com/document/d/1C_wY5ICfTzv7qSLceM-DIENXRHaD2XQC-XSWb4O_JfE/edit
