### ISSUE TITLE
Procure data needed for InVEST model runs

### ISSUE THREAD

**Issue by phargogh** [natcap/urban-online-workflow#12]
Chris sent us some data (https://drive.google.com/drive/u/0/folders/1ZUF_RLc2L-fglFdsJOVg-xSD7J9Gz1BF), but we don't have much information about this.  It would be helpful to document the data we already have and also to procure data needed for running InVEST models in San Antonio.

We also need the wallpapering patterns to use for San Antonio.  Does Chris have these, or will we want to work together to create those?

**Comment by phargogh** [comment]
We chatted about this in our urban checkin meeting yesterday and got a little more information about the datasets present in the [_Data from Chris_](https://drive.google.com/drive/u/0/folders/1ZUF_RLc2L-fglFdsJOVg-xSD7J9Gz1BF) folder on GDrive.  I've [added some short descriptions about the datasets to a Data README](https://docs.google.com/document/d/1PYciQa-1QxMrxnmHmqmuasTjilfRegLvt_BrXCAKuIQ/edit#heading=h.q64lho7b3b7w) in the GDrive folder.

Chris will be back from vacation in July and we have a meeting on the books to settle on some data formats and data sources for national-level InVEST model inputs.

**Comment by phargogh** [comment]
Doug and I worked through the source code for this yesterday and here's what we found:

* Chris has several biophysical tables for the NLCD at `<repo>/naturban/data/parameters/national`, but have been modified for bioregions at `<repo>/naturban/data/parameters`.
* There are only 2 datasets that Chris has scripts to explicitly download:
  * A 10m LULC downloaded from Microsoft: [`development/esri_lulc_10m.py`](https://github.com/chrisnootenboom/urban-workflow/blob/master/development/esri_lulc_10m.py)
  * Temperature data, from Copernicus [`development/cds_api_extraction.py`](https://github.com/chrisnootenboom/urban-workflow/blob/master/development/cds_api_extraction.py)
* Most datasets are just available at a local filepath and it's not clear where the datasets are coming from.
  * ET0
  * NLCD
  * Bioregions

So we'll still need to procure the source datasets.  Except for NLCD, they don't appear to be in the GDrive folder.

**Comment by davemfish** [comment]
It seems like we'll need a "bioregions" dataset to determine which region a given AOI is in. Many of the model's parameter tables include different values for different bioregions.

@chrisnootenboom , I see your reference,
```
bioregions:
    source: /Users/cnootenboom/Library/CloudStorage/GoogleDrive-cnootenb@umn.edu/Shared drives/Urban Workflow/Data/OE_Bioregions.shp
    bioregion: BIOREGION_
    bio_desc: BIOREGIO_1
```
Can you tell us the original source of this dataset?

**Comment by davemfish** [comment]
Closing this general issue in favor more specific ones like #110
