### ISSUE TITLE
Carbon, Urban Nature Access, and Urban Cooling parameter tables need QA/QC

### ISSUE THREAD

**Issue by davemfish** [natcap/urban-online-workflow#133]
Here's one example. This is an excerpt from the parameter table at https://drive.google.com/drive/u/1/folders/1NIeB2h7Zx2zTtu6AtztfVzLR1oP1Hd4a

The glaring thing here is that above-ground carbon stocks do not necessarily increase with higher tree canopy cover.

lucode | LULC_name | nlud_simple_class | nlud_simple_subclass | tree_canopy_cover | c_above | c_below | c_soil | c_dead | c_embedded | c_emissions
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
396 | Developed, Low Intensity | Residential | Suburban | none | 202.9519 | 18.43333 | 93.51444 | 32.980081299999995 | 716.7 | 131.6116
397 | Developed, Low Intensity | Residential | Suburban | low | 186.6761 | 15.66833 | 95.05526 | 29.633069104999997 | 716.7 | 131.6116
398 | Developed, Low Intensity | Residential | Suburban | medium | 159.5498 | 11.06 | 97.6233 | 24.054715446666663 | 716.7 | 131.6116
399 | Developed, Low Intensity | Residential | Suburban | high | 131.33841958059998 | 6.267333 | 100.2941 | 18.25323 | 716.7 | 131.6116

lucode | LULC_name | nlud_simple_class | nlud_simple_subclass | tree_canopy_cover | c_above | c_below | c_soil | c_dead | c_embedded | c_emissions
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
400 | Developed, Medium Intensity | Residential | Suburban | none | 187.4014 | 18.43333 | 92.6556 | 32.76341 | 645.5667 | 489.4527
401 | Developed, Medium Intensity | Residential | Suburban | low | 173.4582 | 15.66833 | 94.32525 | 29.4489 | 645.5667 | 489.4527
402 | Developed, Medium Intensity | Residential | Suburban | medium | 150.21950826399998 | 11.06 | 97.108 | 23.924715444666663 | 645.5667 | 489.4527
403 | Developed, Medium Intensity | Residential | Suburban | high | 126.05126947059999 | 6.267333 | 100.0021 | 18.179560974199998 | 645.5667 | 489.4527

lucode | LULC_name | nlud_simple_class | nlud_simple_subclass | tree_canopy_cover | c_above | c_below | c_soil | c_dead | c_embedded | c_emissions
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
404 | Developed, High Intensity | Residential | Suburban | none | 157.9575 | 18.43333 | 94.35238 | 32.78008 | 1636.85 | 869.1464
405 | Developed, High Intensity | Residential | Suburban | low | 148.43088271149998 | 15.66833 | 95.76751 | 29.46307 | 1636.85 | 869.1464
406 | Developed, High Intensity | Residential | Suburban | medium | 132.55316706399998 | 11.06 | 98.12606127800001 | 23.934715446666665 | 1636.85 | 869.1464
407 | Developed, High Intensity | Residential | Suburban | high | 116.0403 | 6.267333 | 100.57895719620001 | 18.185227641999997 | 1636.85 | 869.1464

There are possibly other issues as well, such as carbon stocks for barren land types, or water bodies, etc.

**Comment by lingling-liu** [comment]
yes I agree. The higher tree canopy, the higher C_above. Will check with Eric tomorrow

**Comment by davemfish** [comment]
It also seems like "c_emissions" should be negative. Or the model should otherwise treat this "pool" differently by subtracting it from the rest.

**Comment by davemfish** [comment]
Done and new data integrated in #139
