### ISSUE TITLE
First deliverable: A demo for creating scenarios

### ISSUE THREAD

**Issue by davemfish** [natcap/urban-online-workflow#16]
We're planning to prepare a demo for the San Antonio group. 

The demo should include the UI & backend necessary for one of us to walk through creating new LULC scenarios and seeing the outcome of that scenario-generation process. It doesn't need to include running invest models. And it doesn't need to run in the cloud.

We estimated that this would be ready in early July. At the time we discussed it, I think that was ~6 weeks away?

**Comment by davemfish** [comment]
Anne may try to get us on their regular San Antonio call scheduled for July 14th. But we're not locked into that yet.

**Comment by phargogh** [comment]
# Backend things to complete

This list is assuming that we're still going to be doing wallpapering

- [ ] #20 
- [ ] Get wallpapering working - endpoints for job submission, status checking and getting the URL to the resulting COG.
   - [ ] New module: `gis_operations` that will be called from the `crud` file.
   - [ ] python function: given WKT bounding box ([related](https://github.com/natcap/wallpaper-scenarios/blob/9d96313b2d01586d5a174105918edcbba2b59e2f/wallpaper_raster.py#L38
)), construct a VRT to grab a subset of the LULC
   - [ ] python function: do wallpapering
- [ ] Implemented a priority queue for jobs (see https://docs.python.org/3/library/heapq.html to start)
- [ ] Design a datastore schema.  Need to define naming conventions for files stored in the bucket or other fileserver.
- [ ] Be able to set up a local development storage backend (a local directory?  Read the storage path in from a config? `file:///./foo` vs `gs://bucketbucket/dir`). JD THINKS THERES A PACKAGE FOR THIS
- [ ] Create a results bucket
- [ ] Deployment process: push changes to repo, server is updated.
- [ ] Cataloging patterns - If users will be creating patterns and descriptions, make it possible to browser other people's patterns.  Need a backend way to store, retrieve a listing of these patterns, specifically (name of pattern, ID of pattern, URL for where the patterned LULC is stored, bbox of pattern, maybe a colorized thumbnail of pixel values (related: can GCS handle many concurrent requests to a big GTiff, or are prerendered thumnails preferable?)

For later, not critical for demo:
- [ ] would be nice if we backed up up the database (later on: disaster recovery plan)
- [ ] Set up cron job for whole-disk snapshots

**Comment by davemfish** [comment]
Seems more useful to make new issues for outstanding items.

**Comment by dcdenu4** [comment]
I agree, I'll make an issue for some of the backend things mentioned in that todo list and then close this issue.

**Comment by dcdenu4** [comment]
Created issue #60 to capture the backend todo tasks for future work.
