### ISSUE TITLE
API for creating scenarios, wallpapers, etc (scenario CRUD)

### ISSUE THREAD

**Issue by davemfish** [natcap/urban-online-workflow#2]
An example of scenario metadata required by the frontend:
```
scenarioID: {
  name: 'project pecan',
  features: {
    0: {
      id: 0,
      table: {
        forest: 23,
        orchard: 50,
        housing: 12,
        commercial: 32,
      },
      action: 'wallpapered with pattern {patternID}',
    },
    1: {
      id: 1,
      ...
    }
  },
  bbox: '[...]', // i.e. of all the features.
  lulc: 'some ref to the lulc created for this scenario',
  base_lulc: 'a ref to the baseline lulc, which could be another scenario's lulc',
},
scenarioID: {
  ...
}
```

**Comment by davemfish** [comment]
**Request to create a session:**
Send:
* 
Receive:
* session ID

**Request to make a scenario:**
Send:
* scenario name & description
* session ID
Receive:
* scenario ID

**Request to update scenario:**
Send:
* scenario ID
* name & description
Receive:
* status

**Delete scenario:**
Send:
* scenario ID
Receive:
* status

**Request Wallpapering:**
Send: 
* (one or more parcels) parcel ID or geometry (depending on where the geometry lives) - start by sending geom from browser
* which pattern to use, 
* which LULC is the baseline
* scenario ID
Receive:
* job ID

**Get Results of Wallpapering:**
Send:
* job ID
Receive:
* url of COG (or whatever) for the new lulc
* summary table of new lulc in parcels (counts per type)

**Get Status of job:** (job could be wallpapering, invest run, etc)
Send:
* job ID
Receive:
* status

**Comment by davemfish** [comment]
I just added a missing endpoint for getting all the metadata for saved scenarios. So we can populate the UI when a session loads. In essence I think that boils down to sending the client the data described in the [first post](https://github.com/natcap/urban-online-workflow/issues/2#issue-1193681566) of this issue.

**Comment by dcdenu4** [comment]
>The only catch is that I'm not sure if this would need to go into the job queue, or if it's possible to just await the response. Maybe it doesn't really matter.

This should be a quick enough operation that we can just await a response. I'm not sure if you'd see any lag if say, 20 other people were trying to make requests. But, we can also throw it onto the PriorityQueue with highest priority too. We still have a bit of work to do to think out the Queue, Job, Worker pipeline.

**Comment by dcdenu4** [comment]
Updating the endpoint for receiving Wallpaper results:

### Get Results of Wallpapering:

_Send:_

- job ID
- scenario ID  <---- added for backend simplicity. It wasn't apparent how to properly connect job_id to a Scenario

_Receive:_

- url of COG (or whatever) for the new lulc
- summary table of new lulc in parcels (counts per type)

**Comment by davemfish** [comment]
I think this issue served it's purpose. We development these endpoints following this design, more or less.
