### ISSUE TITLE
Implement a job queue

### ISSUE THREAD

**Issue by phargogh** [natcap/urban-online-workflow#22]
We need the ability to use a functioning worker queue.  This includes:

- [x] Submitting a job to the queue
- [x] Checking on the status of a job in the queue
- [x] A way to set the priority of a task
- [x] Tracking some result value from a job (like the URL of an output file relative to a storage mechanism's root directory) for returning to a requester

Also, maybe this is a good chance to use python's `heapq`?   https://docs.python.org/3/library/heapq.html

**Comment by dcdenu4** [comment]
This is implemented.
