### ISSUE TITLE
Implement wallpapering in the backend

### ISSUE THREAD

**Issue by phargogh** [natcap/urban-online-workflow#26]
To get wallpapering working, we'll need:
- [ ] endpoints to create a pattern and submit the job to a queue (see #22 )
- [ ] A GIS module `gis_operations` with some basic operations and the wallpapering function code
- [ ] A function to subset NLCD based on a bounding box using a VRT as an intermediary.

Related: https://github.com/natcap/wallpaper-scenarios/blob/9d96313b2d01586d5a174105918edcbba2b59e2f/wallpaper_raster.py#L38

**Comment by dcdenu4** [comment]
@phargogh I'm thinking of the following structure for an endpoint - worker api.

server will create a job with the following json structure that the worker will consume:
```javascript
{
"job": "pattern", 
"server-attrs": {
    "job_id": job_db.job_id, "pattern_id": pattern_db.pattern_id},
 "args": {"wkt": pattern.wkt}
}
```
`job` - the name that identifies the worker function to execute AND the endpoint to call when finished
`server-attrs` - key / values that the server expects to be passed back with the results
`args` - any parameters needed for the `job` function in the worker

The worker upon completion would then call: `some-host/jobsqueue/pattern/` and send along a json object like:
```javascript
{
"result": "some result, could be a path or another object with multiple results",
"status": "success | failed", 
"server-attrs": {
    "job_id": job_db.job_id, "pattern_id": pattern_db.pattern_id},
}
```

Let me know what you think of that format!

**Comment by phargogh** [comment]
Yep, makes sense to me!

**Comment by dcdenu4** [comment]
@phargogh , just an FYI that I'll add a `priority` key to the payload sent to the worker that will have a value of `1 | 2 | 3` with `1` being the highest priority.

**Comment by phargogh** [comment]
@dcdenu4 when we have a `pattern` operation request, can we update the response data like this (just an update to `args`)?

```python
{
"job": "pattern", 
"server-attrs": {
    "job_id": job_db.job_id, "pattern_id": pattern_db.pattern_id},
 "args": {
    "pattern_wkt": pattern.wkt,
    "parcel_wkt": parcel.wkt,  # or however the parcel is stored
    }
}
```

For wallpapering, it feels orthogonal to pass in the parcel WKT as well and then the whole job is self-contained.

**Comment by phargogh** [comment]
We have this implemented!
