### ISSUE TITLE
CORS error in Firefox

### ISSUE THREAD

**Issue by emlys** [natcap/urban-online-workflow#34]
In Firefox, the LULC raster fails to load due to a CORS error. Works fine in Chrome.

**Comment by davemfish** [comment]
Closing this as wontfix because it only needs fixing if someone wants to develop the app using Firefox. The CORS request only occurs in dev when src files are served by the vite dev server. 

https://stackoverflow.com/questions/24514666/why-is-this-cors-request-failing-only-in-firefox
