### ISSUE TITLE
Compare two (or more) LULC rasters

### ISSUE THREAD

**Issue by davemfish** [natcap/urban-online-workflow#4]
We need to visually compare the outcome of the scenario generation process to the baseline LULC. Maybe with two layers on the same map. Or maybe better as two side-by-side map panes. Or something else.

**Comment by dcdenu4** [comment]
I wonder if a "layer swipe" approach would be intuitive? https://openlayers.org/en/latest/examples/layer-swipe.html

**Comment by davemfish** [comment]
I'm placing this on hold because it's not clear that users want to be view LULC rasters at all. In the meantime, we will allow comparisons of scenarios by offering tables that summarize the LULC composition in the parcels that were included in the scenarios.

**Comment by davemfish** [comment]
We display overlays of LULC rasters for each scenario, they can be toggled to facilitate comparison. I think that's good enough for now.
