### ISSUE TITLE
Serve vector tiles

### ISSUE THREAD

**Issue by phargogh** [natcap/urban-online-workflow#5]
We'll need the ability to serve standard map tiles based off of the wallpapered LULC, so it'd be helpful to try out some existing tile servers to see if there's one that better suits our needs.  A quick google search turned up:

* http://tilestache.org/ - Older (last updated in 2019), no explicit GDAL support.  Could work for rendering vector tiles though
* https://github.com/maptiler/tileserver-gl - Newer, more recently updated.  Supports raster and vector tiles.
* https://geoserver.org/ - We should be sure to try this out, kind of the standard tileserver.

**Comment by dcdenu4** [comment]
Related this this, it would be good to have a discussion about the zoom levels we'll need as this can directly effect the size and computation time taken for tiling. For instance Mapbox has a tiling tool called 'tippecanoe' for vector tiling that might be useful. https://github.com/mapbox/tippecanoe#zoom-levels

**Comment by dcdenu4** [comment]
This other mapbox reference might also be useful for thinking about precision: https://docs.mapbox.com/mapbox-tiling-service/guides/#precision-levels-and-square-kilometers

**Comment by emlys** [comment]
I tried out the Mapbox Tiling Service on the San Antonio parcel data with zoom level 16 and it seems good.
* Per the docs, level 16 is good for "block level, restaurant locations, building outlines" which matches our data
* Tiling this dataset at level 16 fell into the 30cm pricing tier, which was free (up to 20,000 km2). Level 17 is in the 1cm tier, which gets expensive quickly.
* Note that you can still zoom in past level 16, it just doesn't load new tiles.

**Comment by davemfish** [comment]
@phargogh It's looking more and more like we'll use REGRID's Tileserver for parcel vectors. So unless we have other vector data that we need on a map, we may not need to setup our own tileserver.

**Comment by phargogh** [comment]
> It's looking more and more like we'll use REGRID's Tileserver for parcel vectors
@davemfish great!  I'm really glad that those tiles will be able to be served through REGRID.

> Depending on scale and usability we still might want to serve our raster outputs (for visualization) via tiles or via a OCG format.
@dcdenu4 and if I remember correctly, it sounded a bit like we might still be needing to convert wallpapered LULCs to vectors in order to serve those to the frontend, right?  If so, a vector tile service might still be relevant.

**Comment by phargogh** [comment]
Sorry, I'm still catching back up on things here coming back to the office.  I thought I remembered from a previous conversation that it would be easier or better (I forget why) for us to render vectors in OpenLayers than it would be to render rasters.  If that's not the case, great!

**Comment by davemfish** [comment]
We're all still learning but I think rendering rasters is just fine for any data where we don't want to interact with features & geometries.

**Comment by dcdenu4** [comment]
Ah! Sorry, I was just thinking of serving raster tiles specifically. I see this issue is "Serve vector tiles".

**Comment by davemfish** [comment]
Now that we're deeper into the project, I don't think we have a need for serving vector tiles at the moment.
