### ISSUE TITLE
Backend DB is currently saved in root

### ISSUE THREAD

**Issue by dcdenu4** [natcap/urban-online-workflow#61]
The `sql_app.db` is currently created in the current working directory from which the `uvicorn` call is made. It looks like right now that command is being run from root and so that's where the DB is created.

I think with:
```
# The working directory
ENV UVICORN_APP_DIR /opt/server
```
in `server/Dockerfile` we're assuming the startup command is being run from `/opt/server`. However, I can't find any reference for `UVICORN_APP_DIR` after a quick google search. @phargogh do you remember the intention here?

I think if we replaced that or added: `WORKDIR /opt/server` then the command could be called from the `/opt/server` directory and that's where the DB would live.

**Comment by phargogh** [comment]
For configuring where the database is stored, then yes, we could do that either by changing the `WORKDIR` in the Dockerfile, or else just change the path in the `./server/sql_app` source code.

`UVICORN_APP_DIR` is a reference to where the uvicorn application source code lives on the filesystem.  Any of the CLI options to uvicorn can be provided by prefixing them with `UVICORN_`, [as discussed in the docs](http://www.uvicorn.org/settings/#settings):

> You can also configure Uvicorn using environment variables with the prefix `UVICORN_`. For example, in case you want to run the app on port `5000`, just set the environment variable `UVICORN_PORT` to `5000`.

There are a variety of other ways uvicorn could have been told where to look for the application source code, including cmdline flags and a configuration file of some sort.  I don't remember why an environment variable seemed like the best solution at the time, but it did work :)

**Comment by dcdenu4** [comment]
Hey James, I'm inclined to go with setting `WORKDIR /opt/server`. A lot of times I debug the API by calling `uvicorn` directly and changing the path in source wouldn't as easily allow for that. Let me know if you think of a reason to avoid `WORKDIR /opt/server`!

**Comment by dcdenu4** [comment]
I set the `WORKDIR` in `server/Dockerfile` to be `opt/server` so that the DB is created in this location. I liked this approach as opposed to setting it up in source because I like to test and debug the endpoint server manually outside of Docker.
