### ISSUE TITLE
wallpapered rasters have the same pattern as the original

### ISSUE THREAD

**Issue by davemfish** [natcap/urban-online-workflow#64]
It doesn't seem like the pattern raster is being applied. I'm looking at the rasters in `appdata/scenarios/`

**Comment by phargogh** [comment]
Weird!  As of rev f5c046d6a458e781893b7604f170f12766338081, I'm getting the correct pixel values in the output rasters.  I also added some logging to the worker to log which file was just written.

**Comment by davemfish** [comment]
@phargogh I'm getting correct values now too, thanks!
