### ISSUE TITLE
Create API endpoint and database diagrams

### ISSUE THREAD

**Issue by dcdenu4** [natcap/urban-online-workflow#69]
Would be useful to see the tables / database we're working to see what data we have access too.

Could this be a wiki? Or use DB Browser for SQLite.

FastAPI generates nice API docs already, but it could be useful to have a paired down version too.

**Comment by davemfish** [comment]
DB Browser is definitely meeting my needs for this.

**Comment by davemfish** [comment]
After working with the database and API a bit, I don't have a need for any documentation beyond what we already have. Want to close this @dcdenu4 ?
