### ISSUE TITLE
managing parcels & study areas in the database

### ISSUE THREAD

**Issue by davemfish** [natcap/urban-online-workflow#71]
I think some small database refactor (or maybe just new endpoints?) will be useful for managing study areas & their parcels. 

Right now, the frontend can get an existing study area and its set of parcels. But it's not so easy to add/remove parcels from that study area. To do so, we are keeping track of the parcel set in react state, and then updating the study area (actually `create_study_area`) with the whole new set of parcels. I think it would be more efficient to have the backend manage more of that, so the frontend could do requests like,

`/{study_area}/add_parcel`
`/{study_area}/remove_parcel`

This would imply that there is _always_ an active study area. So I think the basic flow of requests from the frontend would be:

* `get_session` or `create_session`
* `get_study_areas` - so we can let the user select from existing. And this could probably just get the names, not all the data
* `get_study_area` (if they selected one) or `create_study_area`  - maybe create it without a name at first, so the user doesn't have to think about that right away
* `add_parcel` - which would trigger computing the LULC stats and `get_study_area` - so the frontend gets an updated view of all parcels and their stats in the SA.
* `remove_parcel` and `get_study_area`, again to get an updated view.
* `update_study_area` - so the user can name it, or rename it anytime - and `get_study_area`

And if it makes sense to have `add_parcel` and `remove_parcel` actually be calls to `update_study_area`, with associated arguments, that would be fine too.

**Comment by davemfish** [comment]
> It would also be super useful to have a study area's data include its spatial extent (bounding box of the union of the parcels).

Actually this may not be necessary at all. It could likely be easily handled by openlayers. The objective being able to zoom to the extent of a study area layer.

**Comment by dcdenu4** [comment]
I think the `Parcel` table and `StudyArea` table is set up for managing adding / removing a parcel from a study area.

**Comment by davemfish** [comment]
This was resolved in #74
