### ISSUE TITLE
Processing & displaying invest model results

### ISSUE THREAD

**Issue by davemfish** [natcap/urban-online-workflow#80]
Here's a cheatsheet from Chris with basic metrics he has used to summarize results for each model:

(private link) https://drive.google.com/file/d/1Oe-4o1k6gjZnTa7xJrzfS2unMK1SpFxT/view?usp=share_link

**Comment by dcdenu4** [comment]
I'll take a first stab at designing the backend piece of this.

**Comment by davemfish** [comment]
@dcdenu4 I know this issue is probably more about the infrastructure than about the specific post-processing routines, but we just got feedback from Anne & Eric to prioritize urban cooling, urban nature access, & carbon models once we do get to those routines.

**Comment by dcdenu4** [comment]
When looking through the `invest_model_results.csv` I noticed a `c_emit` and `c_embed` entry for carbon. It would be good to find out what these metrics are referring to from the InVEST model output or if a different carbon model was used.

**Comment by dcdenu4** [comment]
Via our conservation yesterday `c_emit` and `c_embed` come from two custom columns that Chris had in the biophysical pools table. He then just calls `invest.carbon._generate_carbon_map()` directly to get the outputs. The plan is that these metrics might make it into a future PEP. I believe the take away was, it's fine to ignore these for now as they weren't even used in the San Antonio report.

**Comment by davemfish** [comment]
Done in #101
