### ISSUE TITLE
Run invest models with user data

### ISSUE THREAD

**Issue by davemfish** [natcap/urban-online-workflow#85]
We have invest models up & running on sample data. This issue is about running them with the user's actual scenario LULC & whatever other location-specific data & parameters are needed by each model.

See wiki for the list of data requirements by model:
https://github.com/natcap/urban-online-workflow/wiki/Data-for-InVEST,-by-model

And see #12 for discussion about where to find specific data sources.

**Comment by davemfish** [comment]
Based on feedback from Anne & Eric regarding San Antonio partner interests, we should prioritize running urban cooling, urban nature access, & carbon models first.

**Comment by dcdenu4** [comment]
In our conversation yesterday Chris mentioned he would send along some UNA data:
- Attribute table
- Population raster

Also mentioned using one radii for now across all populations.

**Comment by davemfish** [comment]
This is done for urban cooling and carbon. On hold now because getting urban nature access running is a lower priority than working on meaningful results summaries for urban cooling.
