### ISSUE TITLE
Carbon: results summary and valuation

### ISSUE THREAD

**Issue by dcdenu4** [natcap/urban-online-workflow#90]
Currently just interested in using social cost of carbon for valuation. Most interested in the change between scenarios, so we could just aggregate across the whole raster outputs or under Study Area parcels.

This issue breaking out from some previous discussion in #80

**Comment by davemfish** [comment]
On hold until we get some clear direction about what further valuation metrics are important.

**Comment by davemfish** [comment]
#120 will be useful for this
